# Generated by Django 2.1.5 on 2019-04-14 20:37

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_analyst', models.BooleanField(default=False, verbose_name='analyst status')),
                ('is_product_manager', models.BooleanField(default=False, verbose_name='product manager status')),
                ('is_business_manager', models.BooleanField(default=False, verbose_name='business manager status')),
                ('is_plant_manager', models.BooleanField(default=False, verbose_name='plant manager status')),
                ('is_administrator', models.BooleanField(default=False, verbose_name='admin status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('formula_name', models.CharField(default='', max_length=32, unique=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formula_To_Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='', max_length=128, validators=[django.core.validators.RegexValidator('^(\\d*\\.?\\d+)\\s*(\\D.*|)$', code='invalid quantity size', message='quantity size not up to standard')])),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Formula')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalname', models.CharField(default='', max_length=128, unique=True)),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('enable_goal', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(default='', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('package_size', models.CharField(default='', max_length=128, validators=[django.core.validators.RegexValidator('^(\\d*\\.?\\d+)\\s*(\\D.*|)$', code='invalid package size', message='package size not up to standard')])),
                ('cpp', models.FloatField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture_Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_sku_name', models.CharField(default='', max_length=128)),
                ('desired_quantity', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture_line',
            fields=[
                ('ml_name', models.CharField(default='', max_length=32)),
                ('ml_short_name', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\S]{1,5}$', code='invalid Short name', message='Short name can have only Alphabets and Numbers')])),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturing_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'scheduled activity'), ('orphaned', 'orphaned activity')], default='active', max_length=20)),
                ('goal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Goal', to_field='goalname')),
                ('manufacturing_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Manufacture_line')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Line',
            fields=[
                ('product_line_name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=datetime.date.today)),
                ('customer_name', models.CharField(default='', max_length=128)),
                ('sales', models.PositiveIntegerField()),
                ('price_per_case', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(default='')),
                ('groups', models.TextField(default='')),
                ('scheduled_goals', models.TextField(default='')),
                ('unscheduled_goals', models.TextField(default='')),
                ('manufacturing_lines', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('caseupc', models.CharField(default=100000000000, max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12,12}$', code='invalid UPC', message='UPC not 12 digits')])),
                ('unitupc', models.CharField(default=100000000000, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12,12}$', code='invalid UPC', message='UPC not 12 digits')])),
                ('sku_name', models.CharField(default='', max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('unit_size', models.CharField(default='', max_length=128)),
                ('comment', models.TextField(blank=True, null=True)),
                ('formula_scale_factor', models.FloatField(default=1.0)),
                ('manufacture_rate', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1e-07)])),
                ('manufacture_setup_cost', models.DecimalField(decimal_places=2, default=1.0, max_digits=32, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('manufacture_run_cost', models.DecimalField(decimal_places=2, default=1.0, max_digits=32, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('formula', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Formula')),
                ('productline', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Product_Line')),
            ],
        ),
        migrations.CreateModel(
            name='Sku_To_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Customer')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku')),
            ],
        ),
        migrations.CreateModel(
            name='Sku_To_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1.0, max_digits=7)),
                ('ig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Ingredient')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku')),
            ],
        ),
        migrations.CreateModel(
            name='Sku_To_Ml_Shortname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Manufacture_line')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku')),
            ],
        ),
        migrations.CreateModel(
            name='SkuFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sale_record',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku'),
        ),
        migrations.AddField(
            model_name='manufacturing_activity',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku'),
        ),
        migrations.AddField(
            model_name='manufacturing_activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacture_goal',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku'),
        ),
        migrations.AddField(
            model_name='manufacture_goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formula_to_ingredients',
            name='ig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='sku_to_ml_shortname',
            unique_together={('sku', 'ml_short_name')},
        ),
        migrations.AlterUniqueTogether(
            name='sku_to_ingredient',
            unique_together={('sku', 'ig')},
        ),
        migrations.AlterUniqueTogether(
            name='sku_to_customer',
            unique_together={('sku', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='manufacturing_activity',
            unique_together={('user', 'sku', 'goal_name')},
        ),
        migrations.AlterUniqueTogether(
            name='manufacture_goal',
            unique_together={('name', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='formula_to_ingredients',
            unique_together={('formula', 'ig')},
        ),
    ]
