# Generated by Django 2.1.5 on 2019-02-01 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalname', models.CharField(default='', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(default='', max_length=128, unique=True)),
                ('description', models.TextField(null=True)),
                ('package_size', models.CharField(max_length=128, null=True)),
                ('cpp', models.IntegerField(null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture_Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_sku_name', models.CharField(default='', max_length=128)),
                ('desired_quantity', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Line',
            fields=[
                ('product_line_name', models.CharField(default='', max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productline', models.CharField(max_length=256)),
                ('caseupc', models.FloatField(default=1000)),
                ('unitupc', models.FloatField(default=1000, null=True)),
                ('sku_name', models.CharField(default='', max_length=128, unique=True)),
                ('count', models.IntegerField(null=True)),
                ('unit_size', models.CharField(max_length=128, null=True)),
                ('tuples', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sku_To_Customer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Customer')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku')),
            ],
        ),
        migrations.CreateModel(
            name='Sku_To_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Ingredient')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku')),
            ],
        ),
        migrations.CreateModel(
            name='SkuFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product_line',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku'),
        ),
        migrations.AddField(
            model_name='manufacture_goal',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku'),
        ),
        migrations.AddField(
            model_name='manufacture_goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sku_to_ingredient',
            unique_together={('sku', 'ig')},
        ),
        migrations.AlterUniqueTogether(
            name='sku_to_customer',
            unique_together={('sku', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='product_line',
            unique_together={('product_line_name', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='manufacture_goal',
            unique_together={('user', 'sku')},
        ),
    ]
