# Generated by Django 2.1.5 on 2019-02-27 11:14

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('formula_name', models.CharField(default='', max_length=32, unique=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formula_To_Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='', max_length=32)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Formula')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalname', models.CharField(default='', max_length=128, unique=True)),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(default='', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('package_size', models.CharField(max_length=128, null=True)),
                ('cpp', models.FloatField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture_Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_sku_name', models.CharField(default='', max_length=128)),
                ('desired_quantity', models.PositiveIntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture_line',
            fields=[
                ('ml_name', models.CharField(default='', max_length=32)),
                ('ml_short_name', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\S]{1,5}$', code='invalid Short name', message='Short name can have only Alphabets and Numbers')])),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Line',
            fields=[
                ('product_line_name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(default='')),
                ('groups', models.TextField(default='')),
                ('scheduled_goals', models.TextField(default='')),
                ('unscheduled_goals', models.TextField(default='')),
                ('manufacturing_lines', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('caseupc', models.CharField(default=100000000000, max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12,12}$', code='invalid UPC', message='UPC not 12 digits')])),
                ('unitupc', models.CharField(default=100000000000, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12,12}$', code='invalid UPC', message='UPC not 12 digits')])),
                ('sku_name', models.CharField(default='', max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('unit_size', models.CharField(default='', max_length=128)),
                ('comment', models.TextField(blank=True, null=True)),
                ('formula_scale_factor', models.FloatField(default=1.0)),
                ('manufacture_rate', models.FloatField(default=1.0)),
                ('formula', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Formula')),
                ('productline', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Product_Line')),
            ],
        ),
        migrations.CreateModel(
            name='Sku_To_Customer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Customer')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku')),
            ],
        ),
        migrations.CreateModel(
            name='Sku_To_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1.0, max_digits=7)),
                ('ig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Ingredient')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku')),
            ],
        ),
        migrations.CreateModel(
            name='Sku_To_Ml_Shortname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Manufacture_line')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku')),
            ],
        ),
        migrations.CreateModel(
            name='SkuFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='manufacture_goal',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku'),
        ),
        migrations.AddField(
            model_name='manufacture_goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formula_to_ingredients',
            name='ig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='sku_to_ml_shortname',
            unique_together={('sku', 'ml_short_name')},
        ),
        migrations.AlterUniqueTogether(
            name='sku_to_ingredient',
            unique_together={('sku', 'ig')},
        ),
        migrations.AlterUniqueTogether(
            name='sku_to_customer',
            unique_together={('sku', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='manufacture_goal',
            unique_together={('name', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='formula_to_ingredients',
            unique_together={('formula', 'ig')},
        ),
    ]
