# Generated by Django 2.1.5 on 2019-04-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture_goal',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
