# Generated by Django 2.1.5 on 2019-02-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku_to_ingredient',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
