# Generated by Django 2.1.5 on 2019-01-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sku',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='sku_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sku',
            name='tuples',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='unit_size',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='caseupc',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='sku',
            name='unitupc',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
