# Generated by Django 2.1.5 on 2019-01-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('package_size', models.CharField(max_length=128, null=True)),
                ('cpp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sku_to_customer',
            fields=[
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventorymanager.sku')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.customer')),
            ],
        ),
        migrations.CreateModel(
            name='sku_to_ingredients',
            fields=[
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventorymanager.sku')),
                ('ig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.ingredients')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sku_to_ingredients',
            unique_together={('sku_id', 'ig_id')},
        ),
        migrations.AlterUniqueTogether(
            name='sku_to_customer',
            unique_together={('sku_id', 'customer_id')},
        ),
    ]
