# Generated by Django 2.1.5 on 2019-01-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0002_auto_20190120_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='manufacturing_goals',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventorymanager.users')),
                ('desired_quantity', models.IntegerField()),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.sku')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='manufacturing_goals',
            unique_together={('user_id', 'sku_id')},
        ),
    ]
