# Generated by Django 2.1.5 on 2019-01-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0002_auto_20190125_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture_goal',
            name='goal_sku_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
