# Generated by Django 2.1.5 on 2019-02-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0002_sku_to_ingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='productline',
        ),
        migrations.AlterField(
            model_name='product_line',
            name='product_line_name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='product_line',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product_line',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product_line',
            name='sku',
        ),
    ]
