# Generated by Django 2.1.5 on 2019-02-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0002_sku_to_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku_to_ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=7),
        ),
    ]
