# Generated by Django 2.1.5 on 2019-02-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0003_auto_20190205_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='productline',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Product_Line'),
            preserve_default=False,
        ),
    ]
