# Generated by Django 2.1.5 on 2019-04-11 04:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventorymanager', '0003_auto_20190411_0247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacture_Line_Skus',
            new_name='Manufacturing_Actvity',
        ),
        migrations.RenameField(
            model_name='manufacturing_actvity',
            old_name='manufacture_line_short_name',
            new_name='manufacturing_line',
        ),
        migrations.RenameField(
            model_name='manufacturing_actvity',
            old_name='sku_id',
            new_name='sku',
        ),
        migrations.AlterUniqueTogether(
            name='manufacturing_actvity',
            unique_together={('user', 'sku', 'goal_name')},
        ),
    ]
