# Generated by Django 2.1.5 on 2019-01-29 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0003_ingredientfile'),
        ('inventorymanager', '0003_manufacture_goal_goal_sku_name'),
    ]

    operations = [
    ]
