# Generated by Django 2.1.5 on 2019-04-15 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0003_remove_user_is_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
