# Generated by Django 2.1.5 on 2019-02-06 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0004_sku_productline'),
        ('inventorymanager', '0003_auto_20190205_0400'),
    ]

    operations = [
    ]
