# Generated by Django 2.1.5 on 2019-01-29 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0004_merge_20190129_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture_goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
