# Generated by Django 2.1.5 on 2019-04-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0004_auto_20190411_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='enable_goal',
            field=models.BooleanField(default=False),
        ),
    ]
