# Generated by Django 2.1.5 on 2019-01-29 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0004_merge_20190129_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line_name', models.CharField(default='', max_length=128)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product_line',
            unique_together={('product_line_name', 'sku')},
        ),
    ]
