# Generated by Django 2.1.5 on 2019-04-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0004_auto_20190415_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
