# Generated by Django 2.1.5 on 2019-02-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0005_merge_20190206_0302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manufacture_goal',
            unique_together={('name', 'sku')},
        ),
    ]
