# Generated by Django 2.1.5 on 2019-04-15 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0005_auto_20190415_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
