# Generated by Django 2.1.5 on 2019-04-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0005_goal_enable_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturing_actvity',
            name='status',
            field=models.CharField(choices=[('active', 'scheduled activity'), ('orphaned', 'orphaned activity')], default='active', max_length=20),
        ),
    ]
