# Generated by Django 2.1.5 on 2019-04-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0006_auto_20190415_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='timestamp',
            field=models.TextField(default=''),
        ),
    ]
