# Generated by Django 2.1.5 on 2019-01-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0006_skufile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='caseupc',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='sku',
            name='unitupc',
            field=models.FloatField(default=1000, null=True),
        ),
    ]
