# Generated by Django 2.1.5 on 2019-04-14 00:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventorymanager', '0006_manufacturing_actvity_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacturing_Actvity',
            new_name='Manufacturing_Activity',
        ),
    ]
