# Generated by Django 2.1.5 on 2019-01-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0007_auto_20190131_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
