# Generated by Django 2.1.5 on 2019-04-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0007_auto_20190415_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture_goal',
            name='timestamp',
            field=models.TextField(default=''),
        ),
    ]
