# Generated by Django 2.1.5 on 2019-04-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0008_manufacture_goal_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture_line',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturing_activity',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturing_activity',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturing_activity',
            name='status',
            field=models.CharField(choices=[('active', 'scheduled activity'), ('inactive', 'unscheduled activity'), ('orphaned', 'orphaned activity')], default='inactive', max_length=20),
        ),
    ]
