# Generated by Django 2.1.5 on 2019-02-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0008_auto_20190214_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
