# Generated by Django 2.1.5 on 2019-01-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0008_auto_20190131_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_line',
            name='product_line_name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
