# Generated by Django 2.1.5 on 2019-02-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0009_auto_20190214_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
