# Generated by Django 2.1.5 on 2019-02-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0010_auto_20190214_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacture_line',
            name='id',
        ),
        migrations.AlterField(
            model_name='manufacture_line',
            name='ml_short_name',
            field=models.CharField(default='', max_length=5, primary_key=True, serialize=False),
        ),
    ]
