# Generated by Django 2.1.5 on 2019-02-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0011_auto_20190214_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
