# Generated by Django 2.1.5 on 2019-02-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0013_auto_20190214_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_line',
            name='id',
        ),
        migrations.AlterField(
            model_name='product_line',
            name='product_line_name',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
