# Generated by Django 2.1.5 on 2019-02-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0014_auto_20190214_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='productline',
        ),
    ]
