# Generated by Django 2.1.5 on 2019-02-14 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0015_remove_sku_productline'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='product_line',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Product_Line'),
        ),
        migrations.AlterField(
            model_name='product_line',
            name='product_line_name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
