# Generated by Django 2.1.5 on 2019-02-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0018_sku_product_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='product_line',
            new_name='productline',
        ),
    ]
