# Generated by Django 2.1.5 on 2019-02-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0019_auto_20190214_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
