# Generated by Django 2.1.5 on 2019-02-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0020_auto_20190214_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
