# Generated by Django 2.1.5 on 2019-02-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0022_auto_20190214_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
