# Generated by Django 2.1.5 on 2019-02-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0024_auto_20190214_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula_Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1.0, max_digits=7)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Formula')),
                ('ig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Sku_to_Ml_Shortname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Manufacture_line')),
            ],
        ),
        migrations.AddField(
            model_name='sku',
            name='formula_scale_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='sku',
            name='manufacture_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='sku_to_ml_shortname',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku'),
        ),
        migrations.AlterUniqueTogether(
            name='sku_to_ml_shortname',
            unique_together={('sku', 'ml_short_name')},
        ),
        migrations.AlterUniqueTogether(
            name='formula_ingredients',
            unique_together={('formula', 'ig')},
        ),
    ]
