# Generated by Django 2.1.5 on 2019-02-20 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0028_auto_20190218_2325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formula_Ingredients',
            new_name='Formula_To_Ingredients',
        ),
    ]
