# Generated by Django 2.1.5 on 2019-02-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0029_auto_20190220_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula_to_ingredients',
            name='quantity',
            field=models.CharField(default='', max_length=32),
        ),
    ]
