# Generated by Django 2.1.5 on 2019-02-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0030_auto_20190220_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='formula_name',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
