# Generated by Django 2.1.5 on 2019-02-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0031_auto_20190221_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goalname',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
