# Generated by Django 2.1.5 on 2019-02-21 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0032_auto_20190221_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
