# Generated by Django 2.1.5 on 2019-02-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0033_goal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='caseupc',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sku',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sku',
            name='unit_size',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='sku',
            name='unitupc',
            field=models.BigIntegerField(default=0),
        ),
    ]
