# Generated by Django 2.1.5 on 2019-02-22 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0035_auto_20190221_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='caseupc',
            field=models.CharField(default=100000000000, max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12,12}$')]),
        ),
    ]
