# Generated by Django 2.1.5 on 2019-02-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0036_auto_20190222_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='unitupc',
            field=models.BigIntegerField(default=100000000000),
        ),
    ]
