# Generated by Django 2.1.5 on 2019-02-22 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0037_auto_20190222_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture_line',
            name='ml_short_name',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('[A-Za-z0-9]+', message='Password should be a combination of Alphabets and Numbers')]),
        ),
    ]
