# Generated by Django 2.1.5 on 2019-02-22 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0039_auto_20190222_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture_line',
            name='ml_short_name',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('[A-Za-z0-9\\S]{1,5}', code='invalid_short_name', message='Short name Alphabets and Numbers')]),
        ),
    ]
