# Generated by Django 2.1.5 on 2019-02-22 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0041_auto_20190222_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture_line',
            name='ml_short_name',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\S]{1,5}$', message='Short name Alphabets and Numbers')]),
        ),
    ]
