# Generated by Django 2.1.5 on 2019-02-23 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0046_auto_20190222_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='cpp',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='package_size',
            field=models.CharField(default='', max_length=128, validators=[django.core.validators.RegexValidator('^(\\d*\\.?\\d+)\\s*(\\D.*|)$', code='invalid package_size', message='Package size not up to standard')]),
        ),
        migrations.AlterField(
            model_name='manufacture_line',
            name='ml_short_name',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\S]{1,5}$', code='invalid Short name', message='Short name can have only Alphabets and Numbers')]),
        ),
    ]
