# Generated by Django 2.1.5 on 2019-02-24 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0047_auto_20190223_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula_to_ingredients',
            name='quantity',
            field=models.CharField(default='', max_length=128, validators=[django.core.validators.RegexValidator('^(\\d*\\.?\\d+)\\s*(\\D.*|)$', code='invalid quantity size', message='quantity size not up to standard')]),
        ),
        migrations.AlterField(
            model_name='manufacture_goal',
            name='desired_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
