# Generated by Django 2.1.5 on 2019-02-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0049_auto_20190224_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture_goal',
            name='desired_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
