# Generated by Django 2.1.5 on 2019-02-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0050_auto_20190225_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sku',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
