# Generated by Django 2.1.5 on 2019-02-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0051_auto_20190225_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
