# Generated by Django 2.1.5 on 2019-02-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0052_auto_20190225_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula_to_ingredients',
            name='quantity',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cpp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='package_size',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
