# Generated by Django 2.1.5 on 2019-02-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0053_auto_20190225_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
