# Generated by Django 2.1.5 on 2019-02-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0056_scheduler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='data',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='groups',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='items',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='scheduled_goals',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='unscheduled_goals',
            field=models.TextField(default=''),
        ),
    ]
