# Generated by Django 2.1.5 on 2019-02-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0057_auto_20190227_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='manufacturing_lines',
            field=models.TextField(default=''),
        ),
    ]
