# Generated by Django 2.1.5 on 2019-03-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0058_scheduler_manufacturing_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='manufacture_run_cost',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='sku',
            name='manufacture_setup_cost',
            field=models.FloatField(default=1.0),
        ),
    ]
