# Generated by Django 2.1.5 on 2019-03-04 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventorymanager', '0059_auto_20190303_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture_Line_Skus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=0)),
                ('goal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Goal', to_field='goalname')),
                ('manufacture_line_short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Manufacture_line')),
            ],
        ),
        migrations.AlterField(
            model_name='sku',
            name='manufacture_run_cost',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='sku',
            name='manufacture_setup_cost',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=32),
        ),
        migrations.AddField(
            model_name='manufacture_line_skus',
            name='sku_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventorymanager.Sku'),
        ),
        migrations.AddField(
            model_name='manufacture_line_skus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='manufacture_line_skus',
            unique_together={('user', 'sku_id', 'goal_name')},
        ),
    ]
