# Generated by Django 2.1.5 on 2019-03-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0061_auto_20190304_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='formula_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
