# Generated by Django 2.1.5 on 2019-03-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0063_remove_sku_formula_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_record',
            name='customer_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
