# Generated by Django 2.1.5 on 2019-03-26 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0064_auto_20190325_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula_to_ingredients',
            name='quantity',
            field=models.CharField(default='', max_length=128, validators=[django.core.validators.RegexValidator('^(\\d*\\.?\\d+)\\s*(\\D.*|)$', code='invalid quantity size', message='quantity size not up to standard')]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='package_size',
            field=models.CharField(default='', max_length=128, validators=[django.core.validators.RegexValidator('^(\\d*\\.?\\d+)\\s*(\\D.*|)$', code='invalid package size', message='package size not up to standard')]),
        ),
    ]
