# Generated by Django 2.1.5 on 2019-03-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0064_auto_20190325_1657'),
        ('inventorymanager', '0066_auto_20190326_2046'),
    ]

    operations = [
    ]
